name: DEV APP TEST

on: workflow_dispatch

defaults:
  run:
    working-directory: packages/mobile
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://fabernovel/android:api-29-v1.1.0
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
      - uses: actions/setup-python@v2
      - name: Env writer
        run: |
          echo "ENV=DEV" >> .env.dev
      - name: Use Node 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install yarn
        run: npm install -g yarn
        
      - name: Install firebase CLI
        run: npm install -g firebase-tools
  apk:
    runs-on: ubuntu-latest
    steps:
      - name: Env writer
        run: |
          echo "aaaaaaaaaaaaaaaaaaaaaaa"
