name: DEV APP TEST

on: workflow_dispatch

defaults:
  run:
    working-directory: packages/mobile
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://fabernovel/android:api-29-v1.1.0
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
      - uses: actions/setup-python@v2
      - name: Env writer
        run: |
          echo "ENV=DEV" >> .env.dev
      - name: Use Node 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install yarn
        run: npm install -g yarn

      - name: Install firebase CLI
        run: npm install -g firebase-tools

      - name: Install dependencies
        run: yarn

      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew

      - name: Update gradle version for Android
        uses: damienaicheh/update-android-version-gradle-action@v1.0.0
        with:
          build-gradle-path: android/app/build.gradle
          version-code: ${{ github.run_number }}
          print-file: true

      - name: Build Android App Bundle
        run: |
          cd android && ENVFILE=.env.dev ./gradlew assembledevRelease --no-daemon
